# Copyright (c) 2017 ~ 2025, the original author wangl.sir individual Inc,
# All rights reserved. Contact us <Wanglsir@gmail.com, 983708408@qq.com>
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# #### IAM Gateway Example routes-filter configuration. ####
#
spring:
  cloud:
    ## see:org.springframework.cloud.gateway.config.GatewayAutoConfiguration
    ## see:https://cloud.spring.io/spring-cloud-static/spring-cloud-gateway/2.0.0.RELEASE/single/spring-cloud-gateway.html#_requestratelimiter_gatewayfilter_factory
    ## see:https://github.com/eugenp/tutorials/blob/master/spring-cloud/spring-cloud-gateway/src/main/resources/application-webfilters.yml
    ## see:https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/appendix.html
    gateway:
      routes:
        ## see:org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping#lookupRoute()
        ## see:org.springframework.cloud.gateway.filter.factory.FallbackHeadersGatewayFilterFactory
        ## see:https://docs.spring.io/spring-cloud-gateway/docs/2.2.6.RELEASE/reference/html/#fallback-headers
        - id: default-fallback-route
          uri: lb://default-fallback-service
          predicates:
            - Path=/_fallback,/_fallback/**
          filters:
            - name: FallbackHeaders
              args:
                execution-exception-type-header-name: X-Escg-Fail-Type ## Default by 'Execution-Exception-Type'
                execution-exception-message-header-name: X-Escg-Fail-Msg ## Default by 'Execution-Exception-Message'
                root-cause-exception-type-header-name: X-Escg-Fail-Root-Type ## Default by 'Root-Cause-Exception-Type'
                root-cause-exception-message-header-name: X-Escg-Fail-Root-Msg ## Default by 'Root-Cause-Exception-Message'
                cause-exception-message-header-name: X-Escg-Fail-Root-Msg ## Irregular setter method naming?? bug??

        - id: productpage-service-route
          uri: lb://productpage-service
          predicates:
            - Path=/productpage/**
            ## Note: Use the built-in 'WeightCalculatorWebFilter' to implement canary publishing. This should not be the most elegant 
            ## choice. For example, in some scenarios, the client request URL will not change, so it is impossible to implement
            ## canary traffic based on this router. Instead, Escg's dedicated 'CanaryLoadBalancerFilter' should be used, 
            ## which supports dynamic matching of any HTTP request based on SPEL expressions, which is very flexible.
            ## see:https://github.com/spring-cloud/spring-cloud-gateway/pull/215
            #- Weight=v1-productpage-service,5
          filters:
            ## see: org.springframework.cloud.gateway.filter.factory.RewritePathGatewayFilterFactory#apply
            - RewritePath=/productpage/(?<segment>.*),/$\{segment}
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing IpFilter
            ## ------------------------------------------------------
            ###
            - name: IpFilter
              args:
                ## When the white-list (allow) and the CIDR of the black-list (deny) conflict, whether the black-list (deny) has a higher priority.
                preferRejectOnCidrConflict: true ## Default by true
                ## The accept the request when neither the whitelist nor the blacklist match.
                acceptNotMatchCidr: true ## Default by true
                ## The allow all local addresses to pass.
                anyLocalAddressAllowed: true ## Default by true
                statusCode: FORBIDDEN ## Default by HttpStatus.FORBIDDEN
                forwardHeaderNames: ["X-Forwarded-For","Proxy-Client-IP","WL-Proxy-Client-IP","X-Real-IP","REMOTE_ADDR","Remote-Addr","RemoteAddr",
                    "REMOTE_IP","Remote-Ip","RemoteIp","HTTP_X_FORWARDED_FOR","Http-X-Forwarded-For","HttpXForwardedFor","HTTP_X_FORWARDED","Http-X-Forwarded","HttpXForwarded",
                    "HTTP_Client_IP","Http-Client-Ip","HttpClientIp","HTTP_X_CLUSTER_CLIENT_IP","Http-X-Cluster-Client-Ip","HttpXClusterClientIp","HTTP_FORWARDED_FOR",
                    "Http-Forwarded-For","HttpForwardedFor","HTTP_VIA","Http-Via","HttpVia"]
                subnets:
                  - allow: false ## Default by false
                    ## The matching sub-net CIDRs
                    cidrs: ['1.1.1.0/24'] ## Default by []
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing IamRequestSize
            ## ------------------------------------------------------
            ##
            ## Limit for request content-length
            - name: IamRequestSize
              args:
                max-body-size: 5MB ## Default by 5MB
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing FaultInjector
            ## ------------------------------------------------------
            ##
            - name: FaultInjector
              args:
                ## which is equivalent to another and condition after match the SPEL expression.
                percentage: 0.5d ## Default by 1.0d
                ## The enabled fault injector providers.
                provider: Abort ## Default by Abort, Optional(Abort|FixedDelay|RangeDelay)
                ## The request to abort fault injector configuration.
                abort:
                  ## The HttpStatus returned when the fault strategy is meet.
                  statusCode: 500 ## Default by 500
                ## The request to fixed delay fault injector configuration.
                fixedDelay:
                  delayMs: 1000 ## fixed delay in milliseconds, Default by 1000
                ## The request to random range delay fault injector configuration.
                rangeDelay:
                  minDelayMs: 1000 ## Default by 1000
                  maxDelayMs: 5000 ## Default by 5000
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing SimpleSignAuthing
            ## ------------------------------------------------------
            ##
            - name: SimpleSignAuthing
              args:
                ## Note: In some special business platform scenarios, the signature authentication protocol may not define
                ## appId (such as Alibaba Cloud Market SaaS product authentication API), then the uniqueness of the client
                ## application can only be determined according to the request route ID.
                app-id-extractor: Parameter ## Default by 'Parameter', Options(Parameter|RouteId)
                ## Only valid when appId extract mode is parameter.
                app-id-param: appId
                secret-param: appSecret ## Default by 'appSecret'
                sign-replay-verify-enabled: true ## Default by true
                sign-replay-verify-bloom-expire-seconds: 604800 ## Default by 7*24*60*60
                sign-param: sign ## Default by 'sign'
                sign-algorithm: S256 ## Default by 'S256', Options(MD5|S1|S256|S384|S512|HMD5|HS1|HS256|HS512)
                sign-hashing-mode: SimpleParamsBytesSortedHashing ## Default by 'UriParamsKeySortedHashing'
                sign-hashing-include-params: ['*'] ## Default by []
                sign-hashing-exclude-params: ['response_type','__iscg_log'] ## Default by []
                add-sign-auth-client-id-header: X-Sign-Auth-AppId ## Default by 'X-Sign-Auth-AppId'
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing IamRequestLimiter
            ## ------------------------------------------------------
            ##
            - name: IamRequestLimiter
              args:
                #denyEmptyKey: true ## Default are set(recommended)
                #emptyKeyStatus: FORBIDDEN ## Default are set(recommended)
                #statusCode: TOO_MANY_REQUESTS
                ## The available options are: (RedisQuotaLimiter|RedisRateLimiter)
                provider: RedisRateLimiter
                keyResolver:
                  provider: Header ## Default by Host, options are: Host|Path|Principal|Header|Interval
                  properties:
                    ## Note: Be sure to enclose the entire array string in double quotes (to be processed as list<string>),
                    ## otherwise it will be processed as map<string,string>
                    headerNames: "['X-Forwarded-For','Proxy-Client-IP','WL-Proxy-Client-IP']"
            - name: IamRequestLimiter
              args:
                #denyEmptyKey: true ## Default are set(recommended)
                #emptyKeyStatus: FORBIDDEN ## Default are set(recommended)
                #statusCode: TOO_MANY_REQUESTS
                ## The available options are: (RedisQuotaLimiter|RedisRateLimiter)
                provider: RedisRateLimiter
                keyResolver:
                  provider: Principal ## Default by Host, options are: Host|Path|Principal|Header|Interval
                  properties: {}
            - name: IamRequestLimiter
              args:
                #denyEmptyKey: true ## Default are set(recommended)
                #emptyKeyStatus: FORBIDDEN ## Default are set(recommended)
                #statusCode: TOO_MANY_REQUESTS
                ## The available options are: (RedisQuotaLimiter|RedisRateLimiter)
                provider: RedisQuotaLimiter
                keyResolver:
                  provider: Principal ## Default by Host, options are: Host|Path|Principal|Header|Interval
                  properties: {}
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing TrafficReplicator
            ## ------------------------------------------------------
            ##
            - name: TrafficReplicator
              ## More configurations see:com.wl4g.iam.gateway.traffic.TrafficReplicationFilterFactory#applyDefaultToConfig() and prefix: 'spring.iam.gateway.traffic.defaultReplication'
              args:
                targetUris: ["http://localhost:8888/"]
                #wiretap: false ## Default by false
                #connectTimeout: 45_000 ## Default by 45s
                ### see:org.springframework.cloud.gateway.filter.NettyRoutingFilter#getResponseTimeout
                #responseTimeout: 60_000 ## Default by 60s
                #maxHeaderSize: 65535 ## Default no set.
                ##maxInitialLineLength: ## Default by null
                ##proxy:
                ## host:
                ## port:
                ## username:
                ## password:
                ## non-proxy-hosts-pattern:
                #pool:
                #  name: proxy ## Default by proxy
                #  #metrics: true ## Default by false
                #  #max-idle-time: 
                #  #acquire-timeout: 45000 # Default by 45000ms
                #websocket:
                #  proxy-ping: true ## Default by true
                #  max-frame-payload-length: 65535 ## Default no set.
                #  #max-connections: ## Default by: max(availableProcessors(),8)*2)
                #ssl: ## see:org.springframework.cloud.gateway.config.GatewayAutoConfiguration.NettyConfiguration#gatewayHttpClient()
                #  default-configuration-type: TCP ## Default by 'TCP'
                #  handshake-timeout: 10000ms ## Default by 10000ms
                #  close-notify-flush-timeout: 3000ms ## Default by 3000ms
                #  close-notify-read-timeout: 0 ## Default by 0
                #  #key-password: ${spring.cloud.gateway.httpclient.ssl.key-store-password}
                #  #key-store: ## Keystore path for Netty HttpClient.
                #  #key-store-type:
                #  #key-store-password:
                #  #key-store-provider:
                #  #trusted-x509-certificates:
                #  #use-insecure-trust-manager: true ## Default by false
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing ResponseCache
            ## ------------------------------------------------------
            ##
            - name: ResponseCache
              args:
                provider: SimpleCache ## Default by SimpleCache, options(SimpleCache|EhCache|RedisCache)
                simple:
                  ## If you wish the cache should not exceed this number of entries, the cache will evict recently or infrequently
                  ## used entries when it does, WARNING: the cache may evict entries before this limit is exceeded - usually
                  ## when the cache size is close to the limit.
                  maximumSize: 100_000 ## Default by 100_000B
                  ## The expiration interval based on write time, all cache entry reads and writes are updated.
                  expireAfterAccessMs: 60_000 ## Default by 60_000
                  ## The expiration interval based on access time, all cache entries are updated only by write operations.
                  expireAfterWriteMs: 600_000 ## Default by 600_000
                  ## The number of concurrent cache operations, that is, the number of underlying cache block/segment locks.
                  concurrencyLevel: 4 ## Default by 4
                ehcache:
                  ## The cached data elimination algorithm.
                  eliminationAlg: LRU ## Default by LRU, options(LRU|LFU|FIFO)
                  ## The cache name prefix.
                  cacheNamePrefix: ResponseCache ## Default by 'requestCache'
                  ## The number of entries not persisted to keep in memory.
                  offHeapEntries: 100_000 ## Default by 100_000
                  ## The number of data size not persisted to keep in memory. must be less than diskSize
                  offHeapSize: 128MB ## Default by 128MB
                  ## The number of total data size not persisted to keep in disk. must be greater than offHeapSize
                  diskSize: 512MB ## Default by 512MB
                redis:
                  cachePrefix: gateway:responsecache:data
                  expireMs: 60_000
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing IamRetry
            ## ------------------------------------------------------
            ##
            - name: IamRetry
              args:
                retries: 3
                statuses: [BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT]
                methods: GET,POST
                backoff:
                  first-backoff: 100ms
                  max-backoff: 500ms
                  factor: 2
                  based-on-previous-value: false
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing IamCircuitBreaker
            ## ------------------------------------------------------
            ##
            ## see:com.wl4g.iam.gateway.circuitbreaker.IamReactiveResilience4JCircuitBreaker
            ## see:org.springframework.cloud.circuitbreaker.resilience4j.ReactiveResilience4JCircuitBreaker
            ## see:org.springframework.cloud.gateway.filter.factory.SpringCloudCircuitBreakerFilterFactory
            ## see:https://cloud.spring.io/spring-cloud-circuitbreaker/reference/html/spring-cloud-circuitbreaker.html
            ## see:https://github.com/spring-cloud/spring-cloud-gateway/issues/1370
            - name: IamCircuitBreaker
              args:
                name: productpage-service-iamcircuitbreaker
                fallback-uri: forward:/_fallback
                statusCodes:
                  - 500
                  - NOT_FOUND
            ##
            ## ------------------------------------------------------
            ## Filter configuration for testing CanaryLoadBalancer
            ## ------------------------------------------------------
            ##
            - name: CanaryLoadBalancer
              args:
                choose:
                  load-balancer-algorithm: RR ## Options(R|RR|WR|WRR|DH|SH|LC|LT|WLC|WLT)
                probe: ## Default load-balancer configuration. see:com.wl4g.iam.gateway.loadbalance.CanaryLoadBalancerFilterFactory#applyDefault()
                  timeout-ms: 5_000 ## Default by 5_000ms
                  path: /healthz ## Default by '/healthz'
                  expect-statuses: [200,404] ## Default by 200

